### ISSUE TITLE
[Bug🐛] Restore rmcp 3.1 compatibility for MCP and SRE Connector

### ISSUE THREAD

**Issue by mxsm** [mxsm/rocketmq-rust#8942]
### Prerequisites

- [x] I have searched existing issues and discussions
- [x] This is a bug, not a question (use Discussions for questions)

### Environment

- OS: Windows 11 and Linux
- RocketMQ Rust: main branch after #8925 and #8926
- Rust: 1.95.0

### Bug Description

The `rmcp` 3.1 dependency updates removed the `TaskSupport` and `ToolExecution` APIs without migrating the RocketMQ MCP tool catalog or the AI SRE Connector. As a result, both standalone Cargo projects fail to compile. The regression also blocks the disposable Kind stack because its MCP and Connector images cannot be built.

The migration must retain the deny-by-default Tasks boundary. The public capability manifest must continue to advertise `task_support=forbidden`, no Tasks handler may be exposed, and the Connector must reject a manifest that advertises any other task mode.

### Steps to Reproduce

1. Run `cargo check --manifest-path rocketmq-sre/Cargo.toml --locked --workspace`.
2. Run `cargo check --manifest-path rocketmq-tools/rocketmq-mcp/Cargo.toml --locked`.
3. Observe unresolved imports and methods for `TaskSupport`, `ToolExecution`, `with_execution`, or `task_support`.

### Expected vs Actual

**Expected:** Both standalone projects compile with their locked `rmcp` 3.1 dependency while preserving explicit task-forbidden capability metadata and a server surface without Tasks handlers.

**Actual:** Compilation fails because code still targets the removed `rmcp` 2.2 task metadata API.

### Logs/Screenshots

```text
error[E0432]: unresolved import `rmcp::model::TaskSupport`
error[E0599]: no method named `task_support` found for reference `&&rmcp::model::Tool`
```

### Additional Context

Update the MCP catalog, protocol snapshots, and Connector verification tests for the `rmcp` 3.1 model. Keep the business capability field as the fail-closed source of truth, verify read-only annotations on the live tool list, and run both projects' complete validation profiles.
